name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test

    - uses: actions/checkout@v3
      with:
        ref: main
      
    - name: Benchmark baseline
      run: cargo bench --bench benchmark -- --save-baseline main
    
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    
    - name: Benchmarks
      run: cargo bench --bench benchmark -- --baseline main

    - name: Archive benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: criterion-benchmarks
        path: target/criterion
